// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200628144155_intial Migration")]
    partial class intialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Forename")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Surname")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(2020, 6, 28, 15, 41, 54, 958, DateTimeKind.Local).AddTicks(7370),
                            Email = "grant.cooper@example.com",
                            Forename = "Grant",
                            IsActive = true,
                            Surname = "Cooper"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(2020, 6, 28, 15, 41, 54, 965, DateTimeKind.Local).AddTicks(8920),
                            Email = "tom.gathercole@example.com",
                            Forename = "Tom",
                            IsActive = true,
                            Surname = "Gathercole"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(2020, 6, 28, 15, 41, 54, 965, DateTimeKind.Local).AddTicks(8970),
                            Email = "mark.edmondson@example.com",
                            Forename = "Mark",
                            IsActive = true,
                            Surname = "Edmondson"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(2020, 6, 28, 15, 41, 54, 965, DateTimeKind.Local).AddTicks(8970),
                            Email = "graham.clark@example.com",
                            Forename = "Graham",
                            IsActive = true,
                            Surname = "Clark"
                        });
                });

            modelBuilder.Entity("Domain.UserAuditNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Forename")
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UserAuditNotes");
                });
#pragma warning restore 612, 618
        }
    }
}
